services:
  db:
    image: mysql:8.0
    container_name: database-flask-app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flask-app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 36780:8080
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask-app
    env_file:
      - ./app/.env
    volumes:
      - ./app:/flask-todo-app
    depends_on:
      - db
    networks:
      - flask-app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-flask-app
    ports:
      - "80:80"
    depends_on:
      - flask-app
    networks:
      - flask-app-network

volumes:
  mysql:

networks:
  flask-app-network: